function [energy, kinetic, potential] = energy_7_link(z,P) 
%[ENERGY, KINETIC, POTENTIAL] = ENERGY_7_LINK(Z,P)
% 
%FUNCTION:  This function computes the energy of a double
%    pendulum.
%INPUTS: 
%
%
%OUTPUTS: 
%    energy = [1 X nTime] vector of total energy
%    kinetic = [1 X nTime] vector of kinetic energy
%    potential = [1 X nTime] vector of potential energy
% 
%NOTES:
%    This file was automatically generated by writeEnergy.m

g  = P.g ; %gravity
m1 = P.m(1); % Link 1 mass
m2 = P.m(2); % Link 2 mass
m3 = P.m(3); % Link 3 mass
m4 = P.m(4); % Link 4 mass
m5 = P.m(5); % Link 5 mass
m6 = P.m(6); % Link 6 mass
m7 = P.m(7); % Link 7 mass
l1 = P.l(1); % Link 1 length
l2 = P.l(2); % Link 2 length
l3 = P.l(3); % Link 3 length
l4 = P.l(4); % Link 4 length
l5 = P.l(5); % Link 5 length
l6 = P.l(6); % Link 6 length
l7 = P.l(7); % Link 7 length
I1 = P.I(1); % Link 1 moment of inertia about its center of mass
I2 = P.I(2); % Link 2 moment of inertia about its center of mass
I3 = P.I(3); % Link 3 moment of inertia about its center of mass
I4 = P.I(4); % Link 4 moment of inertia about its center of mass
I5 = P.I(5); % Link 5 moment of inertia about its center of mass
I6 = P.I(6); % Link 6 moment of inertia about its center of mass
I7 = P.I(7); % Link 7 moment of inertia about its center of mass
d1 = P.d(1); % Link 1 distance between center of mass and parent joint
d2 = P.d(2); % Link 2 distance between center of mass and parent joint
d3 = P.d(3); % Link 3 distance between center of mass and parent joint
d4 = P.d(4); % Link 4 distance between center of mass and parent joint
d5 = P.d(5); % Link 5 distance between center of mass and parent joint
d6 = P.d(6); % Link 6 distance between center of mass and parent joint
d7 = P.d(7); % Link 7 distance between center of mass and parent joint

th1 = z(1,:); 
th2 = z(2,:); 
th3 = z(3,:); 
th4 = z(4,:); 
th5 = z(5,:); 
th6 = z(6,:); 
th7 = z(7,:); 

dth1 = z(8,:); 
dth2 = z(9,:); 
dth3 = z(10,:); 
dth4 = z(11,:); 
dth5 = z(12,:); 
dth6 = z(13,:); 
dth7 = z(14,:); 

kinetic = (m4.*((d4.*dth4.*sin(th4) + dth1.*l1.*sin(th1) + dth2.*l2.*sin(th2) + dth3.*l3.*sin(th3)).^2 + (dth1.*l1.*cos(th1) + dth2.*l2.*cos(th2) + dth3.*l3.*cos(th3) + d4.*dth4.*cos(th4)).^2))./2 + (m5.*((d5.*dth5.*sin(th5) + dth1.*l1.*sin(th1) + dth2.*l2.*sin(th2) + dth3.*l3.*sin(th3) + dth4.*l4.*sin(th4)).^2 + (dth1.*l1.*cos(th1) + dth2.*l2.*cos(th2) + dth3.*l3.*cos(th3) + dth4.*l4.*cos(th4) + d5.*dth5.*cos(th5)).^2))./2 + (m6.*((d6.*dth6.*sin(th6) + dth1.*l1.*sin(th1) + dth2.*l2.*sin(th2) + dth3.*l3.*sin(th3) + dth4.*l4.*sin(th4) + dth5.*l5.*sin(th5)).^2 + (dth1.*l1.*cos(th1) + dth2.*l2.*cos(th2) + dth3.*l3.*cos(th3) + dth4.*l4.*cos(th4) + dth5.*l5.*cos(th5) + d6.*dth6.*cos(th6)).^2))./2 + (I1.*dth1.^2)./2 + (I2.*dth2.^2)./2 + (I3.*dth3.^2)./2 + (I4.*dth4.^2)./2 + (I5.*dth5.^2)./2 + (I6.*dth6.^2)./2 + (I7.*dth7.^2)./2 + (m7.*((d7.*dth7.*sin(th7) + dth1.*l1.*sin(th1) + dth2.*l2.*sin(th2) + dth3.*l3.*sin(th3) + dth4.*l4.*sin(th4) + dth5.*l5.*sin(th5) + dth6.*l6.*sin(th6)).^2 + (dth1.*l1.*cos(th1) + dth2.*l2.*cos(th2) + dth3.*l3.*cos(th3) + dth4.*l4.*cos(th4) + dth5.*l5.*cos(th5) + dth6.*l6.*cos(th6) + d7.*dth7.*cos(th7)).^2))./2 + (m1.*(d1.^2.*dth1.^2.*cos(th1).^2 + d1.^2.*dth1.^2.*sin(th1).^2))./2 + (m2.*((dth1.*l1.*cos(th1) + d2.*dth2.*cos(th2)).^2 + (d2.*dth2.*sin(th2) + dth1.*l1.*sin(th1)).^2))./2 + (m3.*((dth1.*l1.*cos(th1) + dth2.*l2.*cos(th2) + d3.*dth3.*cos(th3)).^2 + (d3.*dth3.*sin(th3) + dth1.*l1.*sin(th1) + dth2.*l2.*sin(th2)).^2))./2;
potential = g.*m5.*(d5.*sin(th5) + l1.*sin(th1) + l2.*sin(th2) + l3.*sin(th3) + l4.*sin(th4)) + g.*m4.*(d4.*sin(th4) + l1.*sin(th1) + l2.*sin(th2) + l3.*sin(th3)) + g.*m7.*(d7.*sin(th7) + l1.*sin(th1) + l2.*sin(th2) + l3.*sin(th3) + l4.*sin(th4) + l5.*sin(th5) + l6.*sin(th6)) + g.*m3.*(d3.*sin(th3) + l1.*sin(th1) + l2.*sin(th2)) + g.*m6.*(d6.*sin(th6) + l1.*sin(th1) + l2.*sin(th2) + l3.*sin(th3) + l4.*sin(th4) + l5.*sin(th5)) + g.*m2.*(d2.*sin(th2) + l1.*sin(th1)) + d1.*g.*m1.*sin(th1);
energy = potential + kinetic;

end 
