function f = testFile(d1,d2,d3,d4,d5,d6,dth1,dth2,dth3,dth4,dth5,dth6,g,l1,l2,l3,l4,l5,m1,m2,m3,m4,m5,m6,th1,th2,th3,th4,th5,th6)
%TESTFILE
%    F = TESTFILE(D1,D2,D3,D4,D5,D6,DTH1,DTH2,DTH3,DTH4,DTH5,DTH6,G,L1,L2,L3,L4,L5,M1,M2,M3,M4,M5,M6,TH1,TH2,TH3,TH4,TH5,TH6)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    04-Nov-2014 12:56:21

t2 = cos(th1);
t3 = dth2.^2;
t4 = th1-th2;
t5 = sin(t4);
t6 = dth3.^2;
t7 = th1-th3;
t8 = sin(t7);
t9 = dth4.^2;
t10 = th1-th4;
t11 = sin(t10);
t12 = dth5.^2;
t13 = th1-th5;
t14 = sin(t13);
t15 = cos(th2);
t16 = dth6.^2;
t17 = dth1.^2;
t18 = th2-th3;
t19 = sin(t18);
t20 = th2-th4;
t21 = sin(t20);
t22 = th2-th5;
t23 = sin(t22);
t24 = cos(th3);
t25 = th3-th4;
t26 = sin(t25);
t27 = th3-th5;
t28 = sin(t27);
t29 = cos(th4);
t30 = th4-th5;
t31 = sin(t30);
t32 = cos(th5);
t33 = th1-th6;
t34 = sin(t33);
t35 = th2-th6;
t36 = sin(t35);
t37 = th3-th6;
t38 = sin(t37);
t39 = th4-th6;
t40 = sin(t39);
t41 = th5-th6;
t42 = sin(t41);
f = [-d1.*g.*m1.*t2-g.*l1.*m2.*t2-g.*l1.*m3.*t2-g.*l1.*m4.*t2-g.*l1.*m5.*t2-g.*l1.*m6.*t2-d2.*l1.*m2.*t3.*t5-d3.*l1.*m3.*t6.*t8-d4.*l1.*m4.*t9.*t11-d5.*l1.*m5.*t12.*t14-d6.*l1.*m6.*t16.*t34-l1.*l2.*m3.*t3.*t5-l1.*l2.*m4.*t3.*t5-l1.*l2.*m5.*t3.*t5-l1.*l2.*m6.*t3.*t5-l1.*l3.*m4.*t6.*t8-l1.*l3.*m5.*t6.*t8-l1.*l3.*m6.*t6.*t8-l1.*l4.*m5.*t9.*t11-l1.*l4.*m6.*t9.*t11-l1.*l5.*m6.*t12.*t14;-d2.*g.*m2.*t15-g.*l2.*m3.*t15-g.*l2.*m4.*t15-g.*l2.*m5.*t15-g.*l2.*m6.*t15+d2.*l1.*m2.*t5.*t17-d3.*l2.*m3.*t6.*t19-d4.*l2.*m4.*t9.*t21-d5.*l2.*m5.*t12.*t23-d6.*l2.*m6.*t16.*t36+l1.*l2.*m3.*t5.*t17+l1.*l2.*m4.*t5.*t17+l1.*l2.*m5.*t5.*t17+l1.*l2.*m6.*t5.*t17-l2.*l3.*m4.*t6.*t19-l2.*l3.*m5.*t6.*t19-l2.*l3.*m6.*t6.*t19-l2.*l4.*m5.*t9.*t21-l2.*l4.*m6.*t9.*t21-l2.*l5.*m6.*t12.*t23;-d3.*g.*m3.*t24-g.*l3.*m4.*t24-g.*l3.*m5.*t24-g.*l3.*m6.*t24+d3.*l2.*m3.*t3.*t19+d3.*l1.*m3.*t8.*t17-d4.*l3.*m4.*t9.*t26-d5.*l3.*m5.*t12.*t28-d6.*l3.*m6.*t16.*t38+l2.*l3.*m4.*t3.*t19+l2.*l3.*m5.*t3.*t19+l1.*l3.*m4.*t8.*t17+l2.*l3.*m6.*t3.*t19+l1.*l3.*m5.*t8.*t17+l1.*l3.*m6.*t8.*t17-l3.*l4.*m5.*t9.*t26-l3.*l4.*m6.*t9.*t26-l3.*l5.*m6.*t12.*t28;-d4.*g.*m4.*t29-g.*l4.*m5.*t29-g.*l4.*m6.*t29+d4.*l2.*m4.*t3.*t21+d4.*l1.*m4.*t11.*t17+d4.*l3.*m4.*t6.*t26-d5.*l4.*m5.*t12.*t31-d6.*l4.*m6.*t16.*t40+l2.*l4.*m5.*t3.*t21+l2.*l4.*m6.*t3.*t21+l1.*l4.*m5.*t11.*t17+l1.*l4.*m6.*t11.*t17+l3.*l4.*m5.*t6.*t26+l3.*l4.*m6.*t6.*t26-l4.*l5.*m6.*t12.*t31;-d5.*g.*m5.*t32-g.*l5.*m6.*t32+d5.*l2.*m5.*t3.*t23+d5.*l1.*m5.*t14.*t17+d5.*l3.*m5.*t6.*t28+d5.*l4.*m5.*t9.*t31-d6.*l5.*m6.*t16.*t42+l2.*l5.*m6.*t3.*t23+l1.*l5.*m6.*t14.*t17+l3.*l5.*m6.*t6.*t28+l4.*l5.*m6.*t9.*t31;d6.*m6.*(-g.*cos(th6)+l2.*t3.*t36+l3.*t6.*t38+l1.*t17.*t34+l4.*t9.*t40+l5.*t12.*t42)];
