function [A,b,Az,bz] = autoGen_dynamicsNumeric(q1,q2,dq1,dq2,u0,u1,u2,empty)
%AUTOGEN_DYNAMICSNUMERIC
%    [A,B,AZ,BZ] = AUTOGEN_DYNAMICSNUMERIC(Q1,Q2,DQ1,DQ2,U0,U1,U2,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Sep-2015 19:45:58

t2 = q1-q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = dq1.^2;
t6 = cos(q2);
t7 = t6.*u0;
t8 = empty+t4;
t9 = empty-t4;
t10 = dq2.^2;
t11 = t3.*t10;
t12 = t3.*t5;
t13 = sin(q2);
t14 = empty-dq1.*t4.*2.0;
t15 = cos(q1);
t16 = empty-1.0;
A = [empty-t3-2.0;empty-t3;empty-t3-1.0;t16];
if nargout > 1
    b = [empty+t7-u1-t4.*t5+t4.*t10+t15.*u0.*2.0;empty+t7-u2-t4.*t5];
end
if nargout > 2
    Az = [t8;t8;t8;empty;t9;t9;t9;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty;empty];
end
if nargout > 3
    bz = [empty+t11-t3.*t5-u0.*sin(q1).*2.0;empty-t3.*t5;empty-t11+t12-t13.*u0;empty+t12-t13.*u0;t14;t14;empty+dq2.*t4.*2.0;empty;empty+t6+t15.*2.0;empty+t6;t16;empty;empty;t16];
end
