function dz = dynamics(~,z,u,P) 
%DZ = DYNAMICS(T,Z,U,P)
% 
%FUNCTION:  
%    This function computes the dynamics for a point-mass that
%    is connected to the origin by a force actuator.
% 
%INPUTS: 
%    t = time. Dummy input for ode45. Not used.
%    z = [4xn] matrix of states.
%    P = struct of parameters
%OUTPUTS: 
%    dz = [4xn] matrix of state derivatives
% 
%NOTES:
%    This file was automatically generated by write_dynamics

m = P.m; %mass
g  = P.g ; %gravity

r = z(1,:); %distance from point-mass to origin
th = z(2,:); %angle of vector between point-mass and origin
dr = z(3,:); %dr/dt
dth = z(4,:); %dth/dt

ddr = (u + dth.^2.*m.*r - g.*m.*cos(th))./m;
ddth = -(2.*dr.*dth - g.*sin(th))./r;

dz = [...
    dr; %d/dt (distance from point-mass to origin)
    dth; %d/dt (angle of vector between point-mass and origin)
    ddr; %d/dt (dr/dt)
    ddth; %d/dt (dth/dt)
];
end 
