function writeDoublePendulumPosition(p1,p2,g1,g2)

%This function writes the dynamics file for the double pendulum.

filename = 'doublePendulumPosition';

comments{1} = ['[p1,p2,g1,g2] = ' upper(filename) '(Z,P)'];
comments{2} = ' ';
comments{3} = 'FUNCTION:  This function computes the energy of a double';
comments{4} = '    pendulum.';
comments{5}  = 'INPUTS: ';
comments{6} = '    z = [4xn] matrix of states.';
comments{7} = '    P = struct of parameters';
comments{8}  = 'OUTPUTS: ';
comments{9}  = '    p1 = [2xn] position of the end of the first link';
comments{10} = '    p2 = [2xn] position of the end of the second link';
comments{11} = '    g1 = [2xn] position of the CoM of link one';
comments{12} = '    g2 = [2xn] position of the CoM of link two';
comments{13} = ' ';
comments{14} = 'NOTES:';
comments{15} = ['    This file was automatically generated by ' mfilename]; 

params{1} = {'m1','link one mass'};
params{2} = {'m2','link two mass'};
params{3} = {'g ','gravity'};
params{4} = {'l1','link one length'};
params{5} = {'l2','link two length'};
params{6} = {'I1','link one moment of inertia about its center of mass'};
params{7} = {'I2','link two moment of inertia about its center of mass'};
params{8} = {'d1','distance between link one center of mass and parent joint'};
params{9} = {'d2','distance between link two center of mass and parent joint'};

states{1} = {'th1','link one absolute angle'};
states{2} = {'dth1','link one angular rate'};
states{3} = {'th2','link two absolute angle'};
states{4} = {'dth2','link two angular rate'};

%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%
%                               write file                                %
%~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%
fid = fopen([filename '.m'],'w');

fprintf(fid, ['function [p1,p2,g1,g2] = ' filename '(z,P) \n']);

for i=1:length(comments)
    fprintf(fid,['%%' comments{i} '\n']);
end
fprintf(fid,'\n');

for i=1:length(params)
    fprintf(fid,[params{i}{1} ' = P.' params{i}{1} '; %%' params{i}{2} '\n']);
end
fprintf(fid,'\n');

for i=1:length(states)
    fprintf(fid,[states{i}{1} ' = z(' num2str(i) ',:); %%' states{i}{2} '\n']);
end
fprintf(fid,'\n');

fprintf(fid,'n = length(th1); \n');

fprintf(fid,'p1 = zeros(2,n);\n');
fprintf(fid,'p2 = zeros(2,n);\n');
fprintf(fid,'g1 = zeros(2,n);\n');
fprintf(fid,'g2 = zeros(2,n);\n');

fprintf(fid,['p1(1,:) = ' vectorize(char(p1(1))) ';\n']);
fprintf(fid,['p1(2,:) = ' vectorize(char(p1(2))) ';\n']);
fprintf(fid,['p2(1,:) = ' vectorize(char(p2(1))) ';\n']);
fprintf(fid,['p2(2,:) = ' vectorize(char(p2(2))) ';\n']);

fprintf(fid,['g1(1,:) = ' vectorize(char(g1(1))) ';\n']);
fprintf(fid,['g1(2,:) = ' vectorize(char(g1(2))) ';\n']);
fprintf(fid,['g2(1,:) = ' vectorize(char(g2(1))) ';\n']);
fprintf(fid,['g2(2,:) = ' vectorize(char(g2(2))) ';\n']);

fprintf(fid,'\n');
fprintf(fid,'end \n');

fclose(fid);

end


