////////////////////////////////////////////////////////// 
// DO NOT EDIT THIS FILE								// 
//														// 
// It has been automatically generated by:				// 
//     Write_Parameters_File.m							// 
//														// 
// The data and names for the class variables come from // 
// the file Set_Parameters.m and comments can be found  // 
// there.												// 
//														// 
// Written by Matthew Kelly								// 
// matthew.kelly2@gmail.com								// 
////////////////////////////////////////////////////////// 
                                                         


////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////
////  Declare each parameter variable                 ////

//Scalar Variables:
    static double L;
    static double g;
    static double m1;
    static double m2;

//Array Variables:

////                                                  ////
////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////




////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////
////  Assign values to each new parameter variable    ////

//Scalar parameters initialized here
    L = P_dynamics[0];
    g = P_dynamics[1];
    m1 = P_dynamics[2];
    m2 = P_dynamics[3];

//Array initialization goes here
////                                                  ////
////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////

