////////////////////////////////////////////////////////// 
// DO NOT EDIT THIS FILE								// 
//														// 
// It has been automatically generated by:				// 
//     Write_Parameters_File.m							// 
//														// 
// The data and names for the class variables come from // 
// the file Set_Parameters.m and comments can be found  // 
// there.												// 
//														// 
// Written by Matthew Kelly								// 
// matthew.kelly2@gmail.com								// 
////////////////////////////////////////////////////////// 
                                                         


////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////
////  Declare each parameter variable                 ////

//Scalar Variables:

//Array Variables:
    static double P_dynamics[4];

////                                                  ////
////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////



//Get the pointer to the parameters:
double *paramsarray = mxGetPr(params);



////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////
////  Assign values to each new parameter variable    ////

//Scalar parameters initialized here

//Array initialization goes here
    P_dynamics[0] = paramsarray[0];
    P_dynamics[1] = paramsarray[1];
    P_dynamics[2] = paramsarray[2];
    P_dynamics[3] = paramsarray[3];

////                                                  ////
////~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~////

