function [dx,dy] = dynamics(x,y,u)
%DYNAMICS
%    [DX,DY] = DYNAMICS(X,Y,U)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    18-Nov-2014 15:48:29

dx = y.*sin(x)+y.^2;
if nargout > 1
    t2 = cos(x);
    dy = t2.*u+t2.*x+x.*y;
end
