function [A,B] = getLinSys(x,y,u)
%GETLINSYS
%    [A,B] = GETLINSYS(X,Y,U)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    19-Nov-2014 20:59:12

A = reshape([0.0,cos(x),cos(y),0.0],[2, 2]);
if nargout > 1
    B = [sin(u);cos(u)];
end
