function [A,B] = getLinSys(x,y,u)
%GETLINSYS
%    [A,B] = GETLINSYS(X,Y,U)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    18-Nov-2014 15:48:29

t2 = cos(x);
t3 = sin(x);
A = reshape([t2.*y,t2+y-t3.*u-t3.*x,t3+y.*2.0,x],[2, 2]);
if nargout > 1
    B = [0.0;t2];
end
