function [x,dx,ddx] = autoGen_pwPoly5(t,x0,dx0,ddx0,x1,dx1,ddx1)
%AUTOGEN_PWPOLY5
%    [X,DX,DDX] = AUTOGEN_PWPOLY5(T,X0,DX0,DDX0,X1,DX1,DDX1)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    07-Apr-2015 20:18:51

t2 = t-1.0;
t3 = t2.^2;
t4 = t3.^2;
t5 = t.^2;
t6 = t5.^2;
t7 = dx1.*(1.0./5.0);
t8 = t7-x1;
t9 = dx0.*(1.0./5.0);
t10 = t9+x0;
t11 = ddx0.*(1.0./2.0e1);
t12 = dx0.*(2.0./5.0);
t13 = t11+t12+x0;
t14 = ddx1.*(1.0./2.0e1);
t16 = dx1.*(2.0./5.0);
t15 = t14-t16+x1;
x = t.*t4.*t10.*5.0+t2.*t6.*t8.*5.0-t2.*t4.*x0+t.*t6.*x1+t.*t3.*t5.*t15.*1.0e1-t2.*t3.*t5.*t13.*1.0e1;
if nargout > 1
    dx = t4.*t10.*5.0+t6.*t8.*5.0-t4.*x0.*5.0+t6.*x1.*5.0-t3.*t5.*t13.*3.0e1+t3.*t5.*t15.*3.0e1+t.*t2.*t3.*t10.*2.0e1+t.*t2.*t5.*t8.*2.0e1-t.*t2.*t3.*t13.*2.0e1+t.*t5.*t15.*(t.*2.0-2.0).*1.0e1;
end
if nargout > 2
    ddx = ddx0-ddx0.*t.*9.0+ddx1.*t.*3.0+ddx0.*t5.*1.8e1-ddx1.*t5.*1.2e1-dx0.*t.*3.6e1-dx1.*t.*2.4e1+dx0.*t5.*9.6e1+dx1.*t5.*8.4e1-t.*x0.*6.0e1+t.*x1.*6.0e1+t5.*x0.*1.8e2-t5.*x1.*1.8e2-ddx0.*t.*t5.*1.0e1+ddx1.*t.*t5.*1.0e1-dx0.*t.*t5.*6.0e1-dx1.*t.*t5.*6.0e1-t.*t5.*x0.*1.2e2+t.*t5.*x1.*1.2e2;
end
