function [p1,p2] = doublePendulumPosition(th1,th2,l1,l2)
%DOUBLEPENDULUMPOSITION
%    [P1,P2] = DOUBLEPENDULUMPOSITION(TH1,TH2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    12-Oct-2014 21:32:39

t2 = cos(th1);
t3 = l1.*t2;
t4 = sin(th1);
t5 = l1.*t4;
p1 = [t3;t5];
if nargout > 1
    p2 = [t3+l2.*cos(th2);t5+l2.*sin(th2)];
end
