function [energy,kinetic,potential] = doublePendulumEnergy(th1,th2,dth1,dth2,m1,m2,g,l1,l2,I1,I2,d1,d2)
%DOUBLEPENDULUMENERGY
%    [ENERGY,KINETIC,POTENTIAL] = DOUBLEPENDULUMENERGY(TH1,TH2,DTH1,DTH2,M1,M2,G,L1,L2,I1,I2,D1,D2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    12-Oct-2014 21:32:39

t2 = dth1.^2;
t3 = cos(th1);
t4 = d1.^2;
t5 = sin(th1);
t18 = dth1.*l1.*t3;
t19 = cos(th2);
t20 = d2.*dth2.*t19;
t6 = t18+t20;
t8 = sin(th2);
t22 = d2.*dth2.*t8;
t23 = dth1.*l1.*t5;
t7 = t22+t23;
t9 = I1.*t2.*(1.0./2.0);
t10 = dth2.^2;
t11 = I2.*t10.*(1.0./2.0);
t12 = t3.^2;
t13 = t2.*t4.*t12;
t14 = t5.^2;
t15 = t2.*t4.*t14;
t16 = t13+t15;
t17 = m1.*t16.*(1.0./2.0);
t21 = t6.^2;
t24 = t7.^2;
t25 = t21+t24;
t26 = m2.*t25.*(1.0./2.0);
t27 = d2.*t8;
t28 = l1.*t5;
t29 = t27+t28;
t30 = g.*m2.*t29;
t31 = d1.*g.*m1.*t5;
energy = t9+t11+t17+t26+t30+t31;
if nargout > 1
    kinetic = t9+t11+t17+t26;
end
if nargout > 2
    potential = t30+t31;
end
