function [ddth1,ddth2] = doublePendulumDynamics(th1,th2,dth1,dth2,m1,m2,g,l1,I1,I2,d1,d2)
%DOUBLEPENDULUMDYNAMICS
%    [DDTH1,DDTH2] = DOUBLEPENDULUMDYNAMICS(TH1,TH2,DTH1,DTH2,M1,M2,G,L1,I1,I2,D1,D2)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    12-Oct-2014 21:30:53

t2 = d2.^2;
t3 = l1.^2;
t4 = m2.^2;
t7 = th1-th2;
t5 = cos(t7);
t6 = d1.^2;
t8 = cos(th1);
t9 = dth2.^2;
t10 = sin(t7);
t11 = I1.*I2;
t12 = t2.*t3.*t4;
t13 = I2.*m1.*t6;
t14 = I1.*m2.*t2;
t15 = I2.*m2.*t3;
t16 = t5.^2;
t17 = m1.*m2.*t2.*t6;
t18 = t11+t12+t13+t14+t15+t17-t2.*t3.*t4.*t16;
t19 = 1.0./t18;
t20 = dth1.^2;
t21 = cos(th2);
t22 = th1.*2.0;
t23 = t22-th2.*2.0;
t24 = sin(t23);
ddth1 = -t19.*(g.*l1.*t2.*t4.*cos(th1-th2.*2.0).*(-1.0./2.0)+I2.*d1.*g.*m1.*t8+I2.*g.*l1.*m2.*t8+g.*l1.*t2.*t4.*t8.*(1.0./2.0)+t2.*t3.*t4.*t20.*t24.*(1.0./2.0)+I2.*d2.*l1.*m2.*t9.*t10+d1.*g.*m1.*m2.*t2.*t8+d2.*l1.*t2.*t4.*t9.*t10);
if nargout > 1
    ddth2 = d2.*m2.*t19.*(-I1.*g.*t21-g.*m2.*t3.*t21-g.*m1.*t6.*t21+I1.*l1.*t10.*t20+d2.*m2.*t3.*t9.*t24.*(1.0./2.0)+g.*m2.*t3.*t5.*t8+l1.*m2.*t3.*t10.*t20+l1.*m1.*t6.*t10.*t20+d1.*g.*l1.*m1.*t5.*t8);
end
