function ddth = singlePendulumDynamics(th,g,l)
%SINGLEPENDULUMDYNAMICS
%    DDTH = SINGLEPENDULUMDYNAMICS(TH,G,L)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    15-Oct-2014 10:38:25

ddth = -(g.*sin(th))./l;
