function ddth = singlePendulumDynamics(th,g,l)
%SINGLEPENDULUMDYNAMICS
%    DDTH = SINGLEPENDULUMDYNAMICS(TH,G,L)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    12-Oct-2014 19:24:22

ddth = -(g.*sin(th))./l;
