function [ddx,ddy] = autoGen_dynamics(x,y,dx,dy,m1,m2,g)
%AUTOGEN_DYNAMICS
%    [DDX,DDY] = AUTOGEN_DYNAMICS(X,Y,DX,DY,M1,M2,G)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    19-May-2015 22:50:27

t2 = x.^2;
t3 = y.^2;
t4 = t2+t3;
t5 = 1.0./t4.^2;
t6 = m1+m2;
t7 = 1.0./t6;
t8 = t4.^(3.0./2.0);
t9 = g.*t8;
t10 = dy.^2;
t11 = t2.*t10;
t12 = dx.^2;
t13 = t3.*t12;
t14 = t9+t11+t13-dx.*dy.*x.*y.*2.0;
ddx = -m2.*t5.*t7.*t14.*x;
if nargout > 1
    ddy = -m2.*t5.*t7.*t14.*y;
end
